package tech.catenate.orchestra.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClienteCorsoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteCorsoAllPropertiesEquals(ClienteCorso expected, ClienteCorso actual) {
        assertClienteCorsoAutoGeneratedPropertiesEquals(expected, actual);
        assertClienteCorsoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteCorsoAllUpdatablePropertiesEquals(ClienteCorso expected, ClienteCorso actual) {
        assertClienteCorsoUpdatableFieldsEquals(expected, actual);
        assertClienteCorsoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteCorsoAutoGeneratedPropertiesEquals(ClienteCorso expected, ClienteCorso actual) {
        assertThat(expected)
            .as("Verify ClienteCorso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteCorsoUpdatableFieldsEquals(ClienteCorso expected, ClienteCorso actual) {
        assertThat(expected)
            .as("Verify ClienteCorso relevant properties")
            .satisfies(e -> assertThat(e.getMese()).as("check mese").isEqualTo(actual.getMese()))
            .satisfies(e -> assertThat(e.getPagato()).as("check pagato").isEqualTo(actual.getPagato()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteCorsoUpdatableRelationshipsEquals(ClienteCorso expected, ClienteCorso actual) {
        assertThat(expected)
            .as("Verify ClienteCorso relationships")
            .satisfies(e -> assertThat(e.getCliente()).as("check cliente").isEqualTo(actual.getCliente()))
            .satisfies(e -> assertThat(e.getCorso()).as("check corso").isEqualTo(actual.getCorso()));
    }
}
