package tech.catenate.orchestra.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CorsoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAllPropertiesEquals(Corso expected, Corso actual) {
        assertCorsoAutoGeneratedPropertiesEquals(expected, actual);
        assertCorsoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAllUpdatablePropertiesEquals(Corso expected, Corso actual) {
        assertCorsoUpdatableFieldsEquals(expected, actual);
        assertCorsoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAutoGeneratedPropertiesEquals(Corso expected, Corso actual) {
        assertThat(expected)
            .as("Verify Corso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoUpdatableFieldsEquals(Corso expected, Corso actual) {
        assertThat(expected)
            .as("Verify Corso relevant properties")
            .satisfies(e -> assertThat(e.getAnno()).as("check anno").isEqualTo(actual.getAnno()))
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoUpdatableRelationshipsEquals(Corso expected, Corso actual) {}
}
