package tech.catenate.orchestra.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FilmatoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilmatoAllPropertiesEquals(Filmato expected, Filmato actual) {
        assertFilmatoAutoGeneratedPropertiesEquals(expected, actual);
        assertFilmatoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilmatoAllUpdatablePropertiesEquals(Filmato expected, Filmato actual) {
        assertFilmatoUpdatableFieldsEquals(expected, actual);
        assertFilmatoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilmatoAutoGeneratedPropertiesEquals(Filmato expected, Filmato actual) {
        assertThat(expected)
            .as("Verify Filmato auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilmatoUpdatableFieldsEquals(Filmato expected, Filmato actual) {
        assertThat(expected)
            .as("Verify Filmato relevant properties")
            .satisfies(e -> assertThat(e.getBlob()).as("check blob").isEqualTo(actual.getBlob()))
            .satisfies(e -> assertThat(e.getBlobContentType()).as("check blob contenty type").isEqualTo(actual.getBlobContentType()))
            .satisfies(e -> assertThat(e.getNome_file()).as("check nome_file").isEqualTo(actual.getNome_file()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilmatoUpdatableRelationshipsEquals(Filmato expected, Filmato actual) {
        assertThat(expected)
            .as("Verify Filmato relationships")
            .satisfies(e -> assertThat(e.getConcerto()).as("check concerto").isEqualTo(actual.getConcerto()));
    }
}
