package tech.catenate.orchestra.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InsegnanteCorsoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsegnanteCorsoAllPropertiesEquals(InsegnanteCorso expected, InsegnanteCorso actual) {
        assertInsegnanteCorsoAutoGeneratedPropertiesEquals(expected, actual);
        assertInsegnanteCorsoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsegnanteCorsoAllUpdatablePropertiesEquals(InsegnanteCorso expected, InsegnanteCorso actual) {
        assertInsegnanteCorsoUpdatableFieldsEquals(expected, actual);
        assertInsegnanteCorsoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsegnanteCorsoAutoGeneratedPropertiesEquals(InsegnanteCorso expected, InsegnanteCorso actual) {
        assertThat(expected)
            .as("Verify InsegnanteCorso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsegnanteCorsoUpdatableFieldsEquals(InsegnanteCorso expected, InsegnanteCorso actual) {
        assertThat(expected)
            .as("Verify InsegnanteCorso relevant properties")
            .satisfies(e -> assertThat(e.getMese()).as("check mese").isEqualTo(actual.getMese()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsegnanteCorsoUpdatableRelationshipsEquals(InsegnanteCorso expected, InsegnanteCorso actual) {
        assertThat(expected)
            .as("Verify InsegnanteCorso relationships")
            .satisfies(e -> assertThat(e.getInsegnante()).as("check insegnante").isEqualTo(actual.getInsegnante()));
    }
}
